<?php

require ('connect.php'); 

// Check for a valid user ID, through GET or POST:
if ( (isset($_GET['id'] )) && (is_numeric($_GET['id'] )) ) { // From view_users.php
	$id = $_GET['id'] ;
} elseif ( (isset($_POST['id'] )) && (is_numeric($_POST['id'] )) ) { // Form submission.
	$id = $_POST['id'] ;
} else { // No valid ID, kill the script.
	echo '<p class="error">This page has been accessed in error.</p>';
//include footer maybe
	exit();
}

// Retrieve the user's information:
$q = "SELECT * FROM clients WHERE clientid=$id";		
$r = @mysqli_query ($dbc, $q);

if (mysqli_num_rows($r) == 1) { // Valid user ID, show the form.
 
	// Get the user's information:
 $row = mysqli_fetch_array ($r);
	


echo "<a href='list_clients.php'>Go Back to Client List.</a>";

} else { // Not a valid user ID.
	echo '<p class="error">This page has been accessed in error.</p>';
}

?>




<html>

<head>
<link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<?php include('menu.php'); ?>
<div id = "content" align="center"> 
<!-- Create the form: -->
<p>Client Name: <?php echo $row['client_name']; ?></p>
<p>Client City: <?php echo $row['client_city']; ?></p>
<p>Client State: <?php echo $row['client_state']; ?></p>
<p>Address: <?php echo $row['client_address']; ?></p>
<p>City: <?php echo $row['client_city']; ?></p>
<p>State: <?php echo $row['client_state']; ?></p>
<p>Zip Code: <?php echo $row['client_zip']; ?></p>
<p>Contact E-Mail: <?php echo $row['client_email']; ?></p>
<p>Contact Phone: <?php echo $row['client_phone']; ?></p>
<br><br>
<h3>Software Configuration</h3>
<p>Unique Client ID(autogenerated): <?php echo $row['clientid']; ?></p>
<p>HS3 Member ID:<?php echo $row['memberid']; ?></p>
<p>MySQL DB Hostname: <?php echo $row['dbhost']; ?></p>
<p>MySQL DB User: <?php echo $row['dbuser']; ?></p>
<p>MySQL DB Password: <?php echo $row['dbpass']; ?></p>
<pAdmin Interface URL: <?php echo $row['admin_url']; ?></p>
<p>Kaltura Server Url: <?php echo $row['kaltura_url']; ?><br><i> I.E. http://video.wtlw.com/</i></p>
<p>Kaltura Client ID: <?php echo $row['kaltura_pid']; ?><br><i> I.E. 101</i></p>
<p>Kaltura Admin API Secret: <?php echo $row['kadmin_secret']; ?></p>
<p>Kaltura Primary Player ID: <?php echo $row['kplayer']; ?></p>
<p>Wordpress Multisite Server URL: <?php echo $row['wp_url']; ?></p>
<p>Wordpress Blog ID: <?php echo $row['wp_blogid'] ?></p>
<p>Wowza Server URL: <?php echo $row['stream_server'] ?><br><i> I.E. http://streamengine.wosn.tv:1935/</i></p>
<p>Relative Path Where FMLE XML Files: <?php echo $row['xml_path']; ?></p>
<p><input type="submit" name="submit" value="Submit" /></p>
<input type="hidden" name="id" value= <?php echo $id;?>
</form>';
</div>
</body>
</html>